// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIGJSYt6XzH_a4CxakKPHvib3AibuNABw',
    appId: '1:466091754689:web:9fca095477e1760fa70040',
    messagingSenderId: '466091754689',
    projectId: 'wellgo-1',
    authDomain: 'wellgo-1.firebaseapp.com',
    storageBucket: 'wellgo-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRhGV78pdk5dPRUgxcTiAmdymon5Mhp4',
    appId: '1:466091754689:android:b59eefba642d86d4a70040',
    messagingSenderId: '466091754689',
    projectId: 'wellgo-1',
    storageBucket: 'wellgo-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtAx2961orpLpqq4CZKi8-ctRdmM6IaE',
    appId: '1:466091754689:ios:adbffc15a179794aa70040',
    messagingSenderId: '466091754689',
    projectId: 'wellgo-1',
    storageBucket: 'wellgo-1.appspot.com',
    iosBundleId: 'com.example.wellGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtAx2961orpLpqq4CZKi8-ctRdmM6IaE',
    appId: '1:466091754689:ios:adbffc15a179794aa70040',
    messagingSenderId: '466091754689',
    projectId: 'wellgo-1',
    storageBucket: 'wellgo-1.appspot.com',
    iosBundleId: 'com.example.wellGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIGJSYt6XzH_a4CxakKPHvib3AibuNABw',
    appId: '1:466091754689:web:dc690c35d016d713a70040',
    messagingSenderId: '466091754689',
    projectId: 'wellgo-1',
    authDomain: 'wellgo-1.firebaseapp.com',
    storageBucket: 'wellgo-1.appspot.com',
  );
}
